### PR TITLE
Revert "State machine version 0.2"

### PR DESCRIPTION
**Pull request by seraphinatarrant**
Reverts seraphinatarrant/AlexaBots#5

Sorry all! I thought this was merging to develop - my bad.
@SujieZhu did you test this? Did it work for you? If I try it, the inputs I get are `LaunchRequest` which makes sense and `SessionEndedRequest`. 
I looked through the code and there's only one situation where session_ended is True (which ends the session) and that is when it's CancelIntent and StopIntent, and Alexa isn't detecting either of those intents (it mostly doesn't detect an Intent at all and when it does it is ConverseIntent), so I think some of the logic flow is wrong. But it wasn't immediately obvious to me where.  

If you did test it and it worked, maybe my lambdas are being janky - just let me know. If you didn't, you should next time.

### CODE REVIEW

**Comment by SujieZhu** [comment]
I tested the code but not tested the exit cause some other states are not finished yet like changeConstraints and OfferData.

**Comment by seraphinatarrant** [comment]
did you test it in combination with the interaction model or just unit
test?
As in, did you get it to set attributes in the session and give responses?
If so, could you push some example JSON input and output from the test to
`/examples/`?

**Comment by SujieZhu** [comment]
I tested it with your new interaction model. It can set constraints/attributes and give responses.

**Comment by seraphinatarrant** [comment]
Ok cool thanks! We don't need to revert then.
Can you push some of the input and output JSON so I can use it to test
directly?

**Comment by seraphinatarrant** [comment]
@cyoungs apparently also cannot get it to work.  Can you confirm that you are using -
*the latest interaction model
*the latest api
*push the input and output JSON from testing, as requested

**Comment by seraphinatarrant** [comment]
Verified working. Closing - will not revert

**Pull request closed without merging**
